language: php

php:
  - 7.1
  - 7.2
  - 7.3

node_js:
  - "5"

before_script:
  - ./tests/server/start_server.sh
  - sleep 5 # give server some time to start
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

script:
  - vendor/bin/phpunit
